### ISSUE TITLE
Revise WAI-ARIA practices urls

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/website#403]
Recently https://www.w3.org/TR/wai-aria-practices-1.2 was updated with a note that the information had been moved, the intention now seems to be for them to provide an evergreen resource via https://www.w3.org/WAI/ARIA/apg/

> This version of WAI-ARIA Authoring Practices is published to retire it from the Working Group Note track. The content continues to be updated in a format that is more useful to developers: https://www.w3.org/WAI/ARIA/apg/

> The content continues to evolve in that location. The content is no longer versioned, but continuously updated. Improved code examples are also part of that resource

Honestly I think the communication around this is a bit confusing, It’s not clear when to reference [the editors draft](https://w3c.github.io/aria-practices/) over that new AGP resource.

So I’m opening this issue to prompt the conversation. It doesn’t look like there are any plans by the WG to provide redirects so we need to update our URLs one way or the other.

**Comment by donsn** [comment]
The resources at [w3.org/WAI/ARIA/apg](https://www.w3.org/WAI/ARIA/apg/patterns) are case sensitive

An example https://www.w3.org/WAI/ARIA/apg/patterns/Listbox takes you to a 404 page while https://www.w3.org/WAI/ARIA/apg/patterns/listbox takes you to the Listbox widget

I don't know if it's a bug or if that is intentional

**Comment by benoitgrelard** [comment]
These have been updated as we go.
